### ISSUE TITLE
Flow does not show if Sortable Grid is opened in Full Screen Mode

### ISSUE THREAD

**Issue by Bosse-Eigenherd** [getPraxis/FELauncher#15]
Hi,

first of all thanks for this awesome component.
It works perfectly fine when opening it on the Record Detail Page. 
But it does not work, when I click on the Sortable Grid to show it in Full Screen, so that users are able to view Sortable Grids with many columns comfortably. If users go back one screen to the Record Detail Page, the flow shows up.

Is there a possibility to show the flow on the full screen view?

Best regards and thank you!
Bosse

**Comment by darrylingalls** [comment]
@Bosse-Eigenherd sorry for the late response.  I will schedule time within the next two weeks to look into this and see if I can find an answer or fix it.

**Comment by Bosse-Eigenherd** [comment]
Hi @darrylingalls ,

did you have time to find a solution? 
Thank you!

**Comment by ohadios** [comment]
@Bosse-Eigenherd it is not currently possible for us to handle flow events when the screen is open in full screen, as our component is no longer present on the page and therefore not listening to the events.
We have a plan to eventually have a fix for this as a new product altogether, but it will likely be some time before that's available.
