### ISSUE TITLE
Possible cacheing issues with List Multi-Select

### ISSUE THREAD

**Issue by chrisrutter** [getPraxis/FELauncher#17]
Hello. 
Thank you so much for the plugin, it's an incredible bit of work. 
We're using the plugin to change the status of a custom object (delivery tasks) and who they're assigned too. 
When using List Multi-Select, launching the flow works fine. The records change as required, let's call these records, 1 and 2. 
However, when then selecting records 3 and 4 (records 1 and 2 are now no longer selected), and launching the flow once more, records 1, 2, 3 and 4 all change! 
It's as if the records being 'checked' using the multi-select are being cached.
The only option is to hard refresh the page after each flow launch. 

Is this a problem you're aware of?

**Comment by chrisrutter** [comment]
Update! 
We managed to solve this by updating the Enhanced Lightning Grid plugin, seems it was this that was causing this issue.

**Comment by ohadios** [comment]
@chrisrutter yeah, that was a bug we found in Enhanced Lightning Grid, and we even contributed the solution to the open source project, and had Salesforce merge and repackage :)
