### ISSUE TITLE
Hide 'Flow Finished' Modal and Lightning Grid Filter after 'refresh'

### ISSUE THREAD

**Issue by chrisrutter** [getPraxis/FELauncher#18]
Hi! 
Another one from me, more of a question.
We've setup the FELauncher to multi-select but with a simple button which launches an Autolaunched Flow.
When the button is clicked however, the modal window pops up, and within it you get a 'your flow completed successfully', you then have to click the x in the top right corner of the modal which closes it, and refreshes the page. 
Is there a way of 'silently' running the flow, so no modal window popup, then auto refreshing the page when it finishes?

The second issue is around the  `"forcePageRefresh" : true` part of the Event Payload. 
We have records using a date rollup, and a filter on the LightningGrid which removes any records where this data is < today. That way, when we update the records date (with the flow in the first part of this question), they should be filtered out of the LightningGrid.
However, the `"forcePageRefresh" : true` doesn't seem to get rid of these. 
A hard refresh works, or using the refresh button at the top right of the LightningGrid, but using `"forcePageRefresh" : true` doesn't.

Can you suggest anything for this? 

Thanks

**Comment by chrisrutter** [comment]
Very strange! Once again, thank you for your help and support. 
So it's now refreshing perfectly fine.... I'm not sure what the issue was there.

Not to worry about the first question. I've realised that it's probably better as a screen flow anyway.

thanks again.
Chris

**Comment by ohadios** [comment]
Glad to hear everything works as expected!
