### ISSUE TITLE
Using FEL in Console view causes flow to be launched in all tabs that have the FEL component

### ISSUE THREAD

**Issue by ohadios** [getPraxis/FELauncher#3]
I use FEL in console view and have more than one tab or subtab open that has a page with FlowEventListener on it. 
In that scenario the screen flow is launched on each tab, related to the first launch, and must be closed separately. For example if I have FEL on my lightning account page and launch a flow specific to account 1, I will see that flow still open if I click over to account 2, account 3, etc. if they were already open tabs in console.

**Comment by scottlandes1217** [comment]
Is there any news on if there are plans to get this issue fixed? Love the component, but can't really use it until at least this one is fixed. Thanks!!

**Comment by ohadios** [comment]
Scott - good news - we have resolved the issue.
We expect to have an updated package available by next week.

**Comment by scottlandes1217** [comment]
Awesome!! Thanks again!

**Comment by scottlandes1217** [comment]
@ohadios Any update on the release?

**Comment by scottlandes1217** [comment]
@ohadios Do you know when the release is expected?

**Comment by darrylingalls** [comment]
@scottlandes1217 I am currently wrapping up testing.  If all goes well I'll release the package Monday afternoon.

**Comment by scottlandes1217** [comment]
@darrylingalls Sounds great, thanks for the update!

**Comment by darrylingalls** [comment]
@scottlandes1217 new version is up
